stages:
  - test
  - build
  - publish

variables:
  EARTHLY_CI: "true"
  FORCE_COLOR: "1"

test:
  stage: test
  script:
    - earthly +audit
    - earthly +clippy
    - earthly +test
  tags:
    - earthly

build:
  stage: build
  script:
    - earthly -a +build/dist --CI_COMMIT_TAG=$CI_COMMIT_TAG
  artifacts:
    paths:
      - dist/
    expire_in: 6 months
  tags:
    - earthly

upload-s3:
  tags:
    - docker
  stage: publish
  image: docker.git.cornhooves.org/build-tools/deb-s3:latest
  rules:
    - if: "$AWS_SECRET_ACCESS_KEY"
  script:
    - ci/publish-s3.sh
