[package]
name = "perm-watcher"
version = "1.0.1-dev"
authors = ["Robin Schoonover <robin@cornhooves.org>"]
edition = "2018"
publish = false

[dependencies]
clap = "~2.33.0"
chan-signal = "0.3"
env_logger = "0.7"
notify = "5.0.0-pre.2"
libc = "0.2.66"
log = "0.4"

[package.metadata.release]
dev-version-ext="dev"
