[package]
name = "perm-watcher"
version = "1.0.5-dev"
authors = ["Robin Schoonover <robin@cornhooves.org>"]
description = "Change watched file permission bits automatically"
edition = "2018"
publish = false

[dependencies]
clap = "~2.33.0"
env_logger = "0.9"
notify = "=5.0.0-pre.11"
libc = "0.2.66"
log = "0.4"

[package.metadata.release]
dev-version-ext="dev"
post-release-commit-message = """
(cargo-release) start next version {{next_version}}

[ci skip]
"""
