
{% set rust_version="1.88" %}

FROM docker.io/buildpack-deps:stretch AS setup

RUN echo 'deb http://archive.debian.org/debian/ stretch contrib main non-free' > /etc/apt/sources.list

RUN apt-get update \
    && apt-get install -y curl jq build-essential \
    && rm -rf /var/lib/apt/lists/*

RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | \
    sh -s -- -y --default-toolchain {{rust_version}} --profile minimal \
    && /root/.cargo/bin/rustup component add clippy
ENV PATH="/root/.cargo/bin:${PATH}"
ENV CARGO_INCREMENTAL=0

RUN cargo install --locked cargo-audit cargo-make cargo-deb

###

FROM setup AS fetch

RUN mkdir /build
WORKDIR /build
COPY Makefile.toml Cargo.toml Cargo.lock ./
RUN mkdir src && touch src/main.rs
RUN cargo make fetch
COPY . ./

###

FROM fetch AS audit

ARG NOW="{{now()}}"
RUN cargo make audit

###

FROM fetch AS test

RUN cargo clippy
RUN cargo test --all

###

FROM fetch AS build

RUN cargo build --release --color always
ARG REF_TYPE=
RUN REF_TYPE=$REF_TYPE DISTDIR=/dist ci/package.sh
