
[tasks.build-release]
command = "cargo"
args = ["build", "--release"]

[tasks.default]
clear = true
dependencies = [
    "build",
]

[tasks.fetch]
command = "cargo"
args = ["fetch"]

[tasks.package-dist]
command = "ci/package.sh"
dependencies = [
    "build-release"
]
