name: Build
run-name: build
on: [ push ]

jobs:
  build:
    runs-on: bern
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Test
        run: bern --target test
      - name: Build
        run: bern --output dist --build-arg REF_TYPE=${{gitea.ref_type}}
      - name: Archive debian package
        uses: https://gitea.com/actions/upload-artifact@v3
        with:
           name: debian package
           path: dist/*.deb
      - name: Publish debian package
        if: ${{ gitea.ref_type == 'tag' || gitea.ref_name == 'main' }}
        run: curl --user ${{ vars.BOT_LOGIN }}:${{ secrets.BOT_TOKEN }} --upload-file dist/*.deb ${{ gitea.server_url }}/api/packages/${{ github.repository_owner }}/debian/pool/default/${{ gitea.ref_type == 'tag' && 'main' || 'main-dev' }}/upload
